### ISSUE TITLE
Invalid file name for `InteropMemoryHelper`

### ISSUE THREAD

**Issue by kkard2** [NoiseStudio/NoiseEngine#363]
https://github.com/NoiseStudio/NoiseEngine/blob/5172eb170eeaddff80a587140eaf9f77308560e2/NoiseEngine/Interop/MemoryHelper.cs

**Comment by tepdock-github** [comment]
Hello! I'm interested in your project and would like to contribute. Can I have a look at this issue?

**Comment by Vixenka** [comment]
@tepdock-github thank you for being interesting!

In this issue every thing to do is change the name of the linked file to "InteropMemoryHelper.cs", because a type name should suit a file name.
